#!/bin/bash

BinDIR=/home/llr/ilc/shi/data/tb-desy/2025/TB2025-03/eudaq_data/Run_Data
RootDir=/data_ilc/flc/shi/TB_2025_3/TB_Data/convertedfiles
run_start=90624
#run_end=90650
run_end=90624

for (( run=$run_start; run<=$run_end; run++ ))
do
    run_number=$(printf "%06d" $run)
    run_name="eudaq_run_${run_number}"
    if [[ ! -d "${BinDIR}/${run_name}" ]]; then
        echo "Folder ${BinDIR}/${run_name} not found"
        continue
    fi
    if [[ ! -d "${RootDir}/${run_name}" ]]; then
        echo "Folder ${RootDir}/${run_name} not found"
        continue
    fi
    bin_size=$(du -sb "${BinDIR}/${run_name}" | cut -f1)
    root_size=$(du -sb "${RootDir}/${run_name}" | cut -f1)
    if [[ "$bin_size" -le 1048576 ]]; then
        echo " ${BinDIR}/${run_name} : $bin_size <= 1MB"
        continue
    fi
    if [[ "$root_size" -le 1048576 ]]; then
        echo " ${RootDir}/${run_name} : $root_size <= 1MB"
        continue
    fi
    bin_size=$(( $bin_size / (1048576) ))
    root_size=$(( $root_size / (1048576) ))
    #echo RUN: ${run_name} $bin_size"MB "$root_size"MB"
    echo ${run_name} ${RootDir}/${run_name}/*.root

done

